[package]
name = "download-image"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
reqwest = "0.12"
url = "2"
clap = { version = "4.4", features = ["derive"]}